spring:
  application:
    name: calvin
  main:
    banner-mode: off

http:
  enabled: true

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

logging:
  file:
    path: calvin-chess-engine/log/
    name: calvin_debug.log
  level:
    root: WARN
    com.kelseyde.calvin: DEBUG